FROM dockerhub-cn-north-1.jcr.service.jdcloud.com/mysql:5.7
MAINTAINER zyr zyrcc.cn
COPY my.cnf /etc/my.cnf
#RUN mysql -e "grant all privileges on confluence.* to 'confluence'@'%' identified by 'confluence';" &&\
#    mysql -e "grant all privileges on *.* to 'root'@'localhost' identified by 'INCA@inca2020';"
